### ISSUE TITLE
Use web sdk without pop up ?

### ISSUE THREAD

**Issue by krazylearner** [twitterdev/cannonball-web#10]
Hi,
i there any way i can use my input forms with digits web sdk ? Currently it just opens a pop up which does not look good with my website .i want to sent sms and do pin verification using my forms and pages.

Thanks

**Comment by mikebonnell** [comment]
Hey @krazylearner ,

Take a look at here for documentation on our embedded widgit: https://docs.fabric.io/web/digits/embeddable.html

-Mike
