### ISSUE TITLE
Digits Login in chrome extension

### ISSUE THREAD

**Issue by karancy** [twitterdev/cannonball-web#4]
Tried to integrate the Digits login as a chrome extensiona and it doesnt work. The chrome extension doesnt use a http or https protocol to the api. Is there a way for digits to accept 'chrome-extension' protocol or is there some kind of work around?

**Comment by mikebonnell** [comment]
Currently, using Digits within a Chrome Extension is not supported. Thanks for the feedback though will share with the team.
